{{- if and .Values.selfhealing.enable .Values.selfhealing.ticket.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aegis-selfhealing
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  OP_ENDPOINT: "{{ .Values.selfhealing.ticket.endpoint }}"
  AppID: "{{ .Values.selfhealing.ticket.appid }}"
  Token: "{{ .Values.selfhealing.ticket.token }}"
  Ranstr: "{{ .Values.selfhealing.ticket.ranstr }}"
{{- end }}
