apiVersion: v1
kind: ConfigMap
metadata:
  name: aegis-llm
data:
  llm-config.yaml: |
    ai:
      providers:
      - name: openai
        model: "qwen"
        password: "sk-xxxx"
        baseUrl: "https://openai/api"
        temperature: 0.7
        topp: 0.5
        topk: 50
        maxtokens: 32768